// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Jim.iOS
{
	public partial class WebViewController : UIViewController
	{
		public WebViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
